### ISSUE TITLE
Rspec

### ISSUE THREAD

**Issue by jcsporto** [jcsporto/my-study-plan#38]
Mini curso de testes Ruby com Rspec

https://www.youtube.com/watch?v=eb2VaG9bfSE&list=PLdDT8if5attGc3fgFsFe5cvV9MwlVFNLW

- [ ] #1 - Mini curso de testes Ruby com Rspec - Seja bem vindo(a)
- [ ] #2 - Mini curso de testes Ruby com Rspec - O que são testes automatizados
- [ ] #3 - Mini curso de testes Ruby com Rspec - O que é o RSPEC
- [ ] #4 - Mini curso de testes Ruby com Rspec - Criando seu primeiro teste
- [ ] #5 - Mini curso de testes Ruby com Rspec - Desafio do herói #1
- [ ] #6 - Mini curso de testes Ruby com Rspec - Principais elementos do Rspec
    - [ ] - O que são testes e porque eles são importantes
    - [ ] - O que é o Rspec e como utiliza-lo
    - [ ]  - Como integrar o Rspec com o Ruby On Rails 
    - [ ]  - Como testar models
    - [ ] - Como testar controllers
    - [ ] - Como testar API's
- [ ] ...
